DROP TABLE IF EXISTS stream_health_events CASCADE;
DROP TABLE IF EXISTS detections CASCADE;
DROP TABLE IF EXISTS fingerprint_hashes CASCADE;
DROP TABLE IF EXISTS commercials CASCADE;
DROP TABLE IF EXISTS campaigns CASCADE;
DROP TABLE IF EXISTS stations CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP FUNCTION IF EXISTS update_updated_at();
