ALTER TABLE clients
  DROP COLUMN IF EXISTS logo_url,
  DROP COLUMN IF EXISTS cnpj,
  DROP COLUMN IF EXISTS cep,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS city,
  DROP COLUMN IF EXISTS state;
