-- 0024_unify_short_id_drop_detections_fk.up.sql
-- Two changes that unlock the materials fingerprint pipeline (see
-- docs/superpowers/plans/2026-05-13-material-fingerprint-pipeline.md):
--
--   1. Unify short_id sequence across commercials + materials. Both tables
--      currently have independent SERIAL sequences. Once materials enter
--      the in-memory matcher index alongside commercials, two rows with the
--      same short_id (one in each table) would collide. We move both to a
--      single shared sequence, seeded above current MAX.
--
--   2. Drop the detections.commercial_id FK to commercials. The column stays
--      NOT NULL and indexed; it just becomes polymorphic — pointing at
--      commercials.id OR materials.id. Downstream LEFT JOINs already handle
--      missing commercial rows gracefully (see catalog/detections.go).

BEGIN;

-- ────── 1. Shared sequence ──────

CREATE SEQUENCE catalog_short_id_seq AS INTEGER;
-- INTEGER (4-byte) matches the original commercials.short_id and
-- materials.short_id SERIAL types. Capacity is ~2.1B; per §12.2 of the
-- implementation plan (plano_implementacao.md) the projected catalog
-- growth is well under that for the foreseeable future.

-- Seed above MAX of both existing sequences so no future nextval()
-- collides with an existing short_id.
--
-- Guard: setval(seq, 0) is an ERROR ("value 0 is out of bounds, min 1"). When
-- BOTH tables are empty (fresh DB / DR restore-from-scratch) GREATEST(...) would
-- be 0 and this migration would fail mid-apply, leaving the schema dirty and
-- blocking every later migration. So we only setval when there's actual data;
-- on an empty DB the sequence keeps its default (next nextval = 1). On a DB with
-- data the behaviour is unchanged. (Discovered via the 2026-06-17 0039 incident,
-- where this latent bug surfaced in the migrate logs — see
-- docs/incidents/incident-2026-06-17-migration-0039-dirty.md.)
DO $$
DECLARE
    max_short BIGINT;
BEGIN
    SELECT GREATEST(
        COALESCE((SELECT MAX(short_id) FROM commercials), 0),
        COALESCE((SELECT MAX(short_id) FROM materials), 0)
    ) INTO max_short;
    IF max_short > 0 THEN
        PERFORM setval('catalog_short_id_seq', max_short);
    END IF;
END $$;

-- Repoint both tables to the shared sequence. Existing rows are not
-- rewritten — only the DEFAULT changes, plus we orphan the old per-table
-- sequences (kept around for rollback, dropped in a future cleanup).
ALTER TABLE commercials
    ALTER COLUMN short_id SET DEFAULT nextval('catalog_short_id_seq');

ALTER TABLE materials
    ALTER COLUMN short_id SET DEFAULT nextval('catalog_short_id_seq');

-- The old SERIAL-generated sequences (commercials_short_id_seq,
-- materials_short_id_seq) are intentionally kept: SET DEFAULT does NOT
-- change pg_depend ownership, so those sequences remain bound to their
-- columns. They're inert (nothing calls them) but available for the down
-- migration to repoint to via pg_get_serial_sequence().

-- ────── 2. Drop detections.commercial_id FK ──────

-- The constraint name is auto-generated by Postgres. We look it up via
-- information_schema to avoid hard-coding a name that might differ between
-- environments (e.g. test fixture vs prod backup-restore).
DO $$
DECLARE
    fk_name TEXT;
BEGIN
    SELECT tc.constraint_name INTO fk_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_name = 'detections'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'commercial_id';

    IF fk_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE detections DROP CONSTRAINT %I', fk_name);
    END IF;
END $$;

-- An index already exists on detections.commercial_id via the table layout
-- (see migration 0001); we keep it for lookup performance regardless of FK.

COMMIT;
